url: "https://babulcseian.github.io" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "/" # the subpath of your site, e.g. /blog
title: "Md Babul Islam" # the name of your site, e.g. ACME Corp.
description: "Ph.D. Scholar, at Unical"
